### PR TITLE
Remove assumptions about Slot 0 placement and HBA peripheral load order.  

### PR DESCRIPTION
**Pull request by hodor-hodor-hodor**
Remove assumptions about Slot 0 placement and HBA peripheral load order.  

- Allow 'serial_fpga' and its children to be loaded starting from any slot, and in any peripheral order.  
- Allow multiple serial_fpga devices.
- Move "hba.h" from EEDD to Peripherals.  

_Assigns fixed CoreID numbers to peripherals which, once assigned, should not be reused._

**Flexible peripheral load order is a prerequisite for future development of FPGA peripheral enumeration.** 

**This change should make the HBA Peripherals completely EEDD compatible, eliminating
the need to maintain HBA-specific versions of the Daemon code.**

### CODE REVIEW

**Comment by bblodget** [comment]
This looks cool.  Does it require a corresponding patch to EEDD?

**Comment by hodor-hodor-hodor** [comment]
:) Yes,  I have a matching eedd patch, which removes the explicit loading of the peripheral modules, but it is not a prerequisite to this peripherals change.   This change remains backward compatible.

I think the EEDD merge request will wait until the actual automatic Enumeration is implemented, in Phase 2.

For the Phase-2 changes,  I'm thinking that serial_fpga.v could be updated to return a simple bit-mapped indication of which fixed core-ids are actually present in the FPGA.  The serial_fpga.c would then load only those appropriate .so files.

**Comment by hodor-hodor-hodor** [comment]
I big help would be for "someone" to rebase the 'hba' branch of eedd, to 'master'.   That way I can just deal with the *.so loader diffs between the two branches.

**Comment by bob-dpi** [comment]
The idea of the empty daemon is that it is, well, empty.  Any code that is specific to HBA has to remain in the HBA branch.  I hope this makes sense.

**Comment by hodor-hodor-hodor** [comment]
Hi Bob, 

I haven't looked in a few weeks, but when I last I tried to rebase 'hba' onto the latest 'master', there were a lot of differences between the two branches in the base eedd code itself. i.e. Fixes made on one branch and not on the other.  None of these fixes should be 'hba' specific or 'hba' unique.    I didn't feel qualified to reconcile those core code diffs.  Any expertise you can provide to help reconcile the two branches would be much appreciated.

> The idea of the empty daemon is that it is, well, empty.

Understood, that is my goal also.  I'd like to make the 'hba' branch unnecessary, and/or have the 'hba' branch's only changes being: 

1. The 'hba' command name prefix, in the Makefile. 
2. The name of the (single) .so loaded at boot time.
3. Makefile changes to also clean/build/install '../peripherals'.

Nothing else should be hba specific or hba required, just those 2-3 extra commits, routinely rebased onto 'master'.

- A -

**Comment by bob-dpi** [comment]
On 11/13/19 3:42 PM, Anonymous Gentleman Maker wrote:
> I haven't looked in a few weeks, but when I last I tried to rebase 'hba' onto the latest 'master', there were a lot of differences between the two branches in the base eedd code itself. i.e. Fixes made on one branch and not on the other.  None of these fixes should be 'hba' specific or 'hba' unique.    I didn't feel qualified to reconcile those core code diffs.  Any expertise you can provide to help reconcile the two branches would be much appreciated.

Ah. I will reconcile eedd with the hba branch.
Thanks.

**Comment by bob-linuxtoys** [comment]
Andy, yeah, wow there was a lot of DPI stuff in master that should never have been there.  I _think_ I've cleaned it all out and done the rebase correctly.   Please let me know if you find any errors.

**Pull request merged**
